### login
POST http://127.0.0.1:8000/api/login
Content-Type: : application/json
Accept: application/json

{
    "email":"te_testeoTE@gmail.com",
    "password":"Pepito1253"
}

### logout
POST http://127.0.0.1:8000/api/logout
Accept: application/json
Authorization: Bearer 7|H7ReRKl7BfWTAE0q3Y1uX5MrE491bnBJ1oxvUDF030e10ec6
